/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schemas/schema.json
export type BlogReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blog";
};

export type BlogCarouselSection = {
  _type: "blogCarouselSection";
  overline?: string;
  title?: string;
  description?: string;
  items?: Array<{
    _key: string;
  } & BlogReference>;
};

export type FaqSection = {
  _type: "faqSection";
  overline?: string;
  title?: string;
  description?: string;
  faqItems?: Array<{
    question?: string;
    answer?: PortableText;
    _type: "faqItem";
    _key: string;
  }>;
};

export type PageSections = Array<{
  _key: string;
} & FaqSection | {
  _key: string;
} & BlogCarouselSection>;

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type VideoObject = {
  _type: "videoObject";
  type?: "embed" | "file";
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  embed?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageObject = {
  _type: "imageObject";
  file?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type GeneralPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "generalPage";
};

export type AllBlogsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "allBlogsPage";
};

export type PortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    addLink?: boolean;
    openNewTab?: boolean;
    label?: string;
    type?: "internal" | "external";
    href?: string;
    reference?: HomePageReference | GeneralPageReference | BlogReference | AllBlogsPageReference;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  _key: string;
} & ImageObject | {
  _key: string;
} & VideoObject | {
  embedLink?: string;
  _type: "iframe";
  _key: string;
} | {
  title?: string;
  _type: "contentTableBlock";
  _key: string;
}>;

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuLinks?: Array<{
    addLink?: boolean;
    disabled?: boolean;
    openNewTab?: boolean;
    label?: string;
    type?: "internal" | "external";
    href?: string;
    reference?: HomePageReference | GeneralPageReference | BlogReference | AllBlogsPageReference;
    _type: "menuLink";
    _key: string;
  }>;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  menuLinks?: Array<{
    addLink?: boolean;
    disabled?: boolean;
    openNewTab?: boolean;
    label?: string;
    type?: "internal" | "external";
    href?: string;
    reference?: HomePageReference | GeneralPageReference | BlogReference | AllBlogsPageReference;
    _type: "menuLink";
    _key: string;
  }>;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageSections?: PageSections;
};

export type GeneralPage = {
  _id: string;
  _type: "generalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  pageSections?: PageSections;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  title?: string;
  isFeaturedBlog?: boolean;
  blogAuthor?: AuthorReference;
  description?: string;
  beforeBlogContentSections?: PageSections;
  blogContent?: PortableText;
  afterBlogContentSections?: PageSections;
};

export type AllBlogsPage = {
  _id: string;
  _type: "allBlogsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  beforeBlogListSections?: PageSections;
  afterBlogListSections?: PageSections;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fullName?: string;
  description?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = BlogReference | BlogCarouselSection | FaqSection | PageSections | SanityFileAssetReference | VideoObject | SanityImageAssetReference | ImageObject | HomePageReference | GeneralPageReference | AllBlogsPageReference | PortableText | Footer | Header | HomePage | GeneralPage | AuthorReference | Blog | AllBlogsPage | SanityImageCrop | SanityImageHotspot | Author | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../../packages/sanity-queries/src/allBlogs.ts
// Variable: ALL_BLOG_QUERY
// Query: *[_type == "allBlogsPage"][0]{  _createdAt, _id, afterBlogListSections[0]{    description, title  }, beforeBlogListSections[0]{    "bgImage": bgImage.file.asset->url,    description,    title  }}
export type ALL_BLOG_QUERY_RESULT = {
  _createdAt: string;
  _id: string;
  afterBlogListSections: {
    description: string | null;
    title: string | null;
  } | null;
  beforeBlogListSections: {
    bgImage: null;
    description: string | null;
    title: string | null;
  } | null;
} | null;

// Source: ../../packages/sanity-queries/src/blog.ts
// Variable: BLOG_QUERY
// Query: *[_type == 'blog'][]{  _id, "slug" : slug.current, "author": blogAuthor -> fullName, blogContent, description, title}
export type BLOG_QUERY_RESULT = Array<{
  _id: string;
  slug: string | null;
  author: string | null;
  blogContent: PortableText | null;
  description: string | null;
  title: string | null;
}>;

// Source: ../../packages/sanity-queries/src/blog.ts
// Variable: SINGLE_BLOG_QUERY
// Query: *[_type == "blog"  && slug.current == $slug ][0]{  _id, "slug" : slug.current, "author": blogAuthor -> fullName, blogContent, description, title}
export type SINGLE_BLOG_QUERY_RESULT = {
  _id: string;
  slug: string | null;
  author: string | null;
  blogContent: PortableText | null;
  description: string | null;
  title: string | null;
} | null;

// Source: ../../packages/sanity-queries/src/home.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == "homePage"][0]{  pageSections[0]{    "bgImage": bgImage.file.asset->url,    description,    title  }}
export type HOME_PAGE_QUERY_RESULT = {
  pageSections: {
    bgImage: null;
    description: string | null;
    title: string | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"allBlogsPage\"][0]{\n  _createdAt, _id, afterBlogListSections[0]{\n    description, title\n  }, beforeBlogListSections[0]{\n    \"bgImage\": bgImage.file.asset->url,\n    description,\n    title\n  }\n}": ALL_BLOG_QUERY_RESULT;
    "*[_type == 'blog'][]{\n  _id, \"slug\" : slug.current, \"author\": blogAuthor -> fullName, blogContent, description, title\n}": BLOG_QUERY_RESULT;
    "*[_type == \"blog\"  && slug.current == $slug ][0]{\n  _id, \"slug\" : slug.current, \"author\": blogAuthor -> fullName, blogContent, description, title\n}": SINGLE_BLOG_QUERY_RESULT;
    "*[_type == \"homePage\"][0]{\n  pageSections[0]{\n    \"bgImage\": bgImage.file.asset->url,\n    description,\n    title\n  }\n}": HOME_PAGE_QUERY_RESULT;
  }
}

